rules:
  anonymous-definition:
    # https://docs.zizmor.sh/audits/#anonymous-definition
    disable: true
  concurrency-limits:
    # https://docs.zizmor.sh/audits/#concurrency-limits
    disable: true
  undocumented-permissions:
    # https://docs.zizmor.sh/audits/#undocumented-permissions
    disable: true
