name: Arch Linux

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache for Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-arch-${{ hashFiles('Vagrantfile') }}
          restore-keys: vagrant-arch-
      - name: Run integration tests
        run: make test-arch
