name: Arch Linux

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

permissions: {}

jobs:
  test:
    # VirtualBox is contained only in macos-12.
    # See https://github.com/actions/runner-images/tree/main/images/macos
    runs-on: macos-12
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run integration tests
        run: make test-arch
        env:
          SETUP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
