name: Arch Linux

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    # VirtualBox is contained only in macos-12.
    # See https://github.com/actions/runner-images/tree/main/images/macos
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v5
      - name: Run integration tests
        run: make test-arch
        env:
          SETUP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
