name: Debian

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    # macos-latest (== macos-11) doesn't contain virtualbox and vagrant at this point.
    # See https://github.com/actions/runner-images/tree/main/images/macos
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Cache for Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-debian-${{ hashFiles('Vagrantfile') }}
          restore-keys: vagrant-debian-
      - name: Run integration tests
        run: make test-debian
        env:
          SETUP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
