name: macOS

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run integration tests
        run: |
          sh -ex macos.sh -h
          sh -ex macos.sh --dot-ssh test/dot.ssh --git-user-name foobar --git-user-email foobar@test.example
        env:
          SETUP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
